config/routes.rb
BrainCandyApp::Application.routes.draw do
  resources :brain_candies

  root to: "brain_candies#index"

end

app/models/brain_candy.rb
class BrainCandy < ActiveRecord::Base
  attr_accessible :name, :difficulty_level_id

  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false

  belongs_to :difficulty_level

  delegate :name, to: :difficulty_level, prefix: true, allow_nil: true
end

app/models/difficulty_level.rb
class DifficultyLevel < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brain_candies_controller.rb
class BrainCandiesController < ApplicationController
  # GET /brain_candies
  # GET /brain_candies.json
  def index
    @brain_candies = BrainCandy.includes(:difficulty_level).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brain_candies }
    end
  end

  # GET /brain_candies/1
  # GET /brain_candies/1.json
  def show
    @brain_candy = BrainCandy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brain_candy }
    end
  end

  # GET /brain_candies/new
  # GET /brain_candies/new.json
  def new
    @brain_candy = BrainCandy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brain_candy }
    end
  end

  # GET /brain_candies/1/edit
  def edit
    @brain_candy = BrainCandy.find(params[:id])
  end

  # POST /brain_candies
  # POST /brain_candies.json
  def create
    @brain_candy = BrainCandy.new(params[:brain_candy])

    respond_to do |format|
      if @brain_candy.save
        format.html { redirect_to @brain_candy, notice: 'Brain candy was successfully created.' }
        format.json { render json: @brain_candy, status: :created, location: @brain_candy }
      else
        format.html { render action: "new" }
        format.json { render json: @brain_candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brain_candies/1
  # PUT /brain_candies/1.json
  def update
    @brain_candy = BrainCandy.find(params[:id])

    respond_to do |format|
      if @brain_candy.update_attributes(params[:brain_candy])
        format.html { redirect_to @brain_candy, notice: 'Brain candy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brain_candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brain_candies/1
  # DELETE /brain_candies/1.json
  def destroy
    @brain_candy = BrainCandy.find(params[:id])
    @brain_candy.destroy

    respond_to do |format|
      format.html { redirect_to brain_candies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brain_candies_helper.rb
module BrainCandiesHelper
end

app/views/brain_candies/_form.html.erb
<%= bootstrap_form_for(@brain_candy) do |f| %>
    <%= f.alert_message "Please fix the errors below" %>
    <%= f.text_field :name, placeholder: "hello" %>
    <%= f.select :difficulty_level_id, DifficultyLevel.all.map{|dl| [dl.name, dl.id]} %>

    <%= f.actions do %>
        <%= f.submit "Submit" %>
    <% end %>
<% end %>

app/views/brain_candies/edit.html.erb
<h1>Editing brain_candy</h1>

<%= render 'form' %>

<%= link_to 'Show', @brain_candy %> |
<%= link_to 'Back', brain_candies_path %>

app/views/brain_candies/index.html.erb
<h1>Listing brain_candies</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Difficulty Level</th>
    <th></th>
  </tr>

  <% @brain_candies.each do |brain_candy| %>
      <tr>
        <td><%= brain_candy.name %></td>
        <td><%= brain_candy.difficulty_level_name %></td>
        <td>
          <%= link_to 'Show', brain_candy %> |
          <%= link_to 'Edit', edit_brain_candy_path(brain_candy) %> |
          <%= link_to 'Destroy', brain_candy, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Brain candy', new_brain_candy_path %>

app/views/brain_candies/new.html.erb
<h1>New brain_candy</h1>

<%= render 'form' %>

<%= link_to 'Back', brain_candies_path %>

app/views/brain_candies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brain_candy.name %>
</p>


<%= link_to 'Edit', edit_brain_candy_path(@brain_candy) %> |
<%= link_to 'Back', brain_candies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "BrainCandy" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->

</div>
<!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>